Fix missing UserHandle symbol
UserHandle error: cannot find symbol

frameworks/base/packages/SystemUI/src/com/android/keyguard/KeyguardPinViewController.java:73: error: cannot find symbol
        Settings.System.LOCKSCREEN_QUICK_UNLOCK_CONTROL, 0, UserHandle.USER_CURRENT) == 1);
                                                            ^
  symbol:   variable UserHandle
  location: class KeyguardPinViewController